# Copyright (c) 2025, Teciza and contributors
# For license information, please see license.txt

from frappe.custom.doctype.custom_field.custom_field import create_custom_fields


def execute():
	create_custom_fields(
		{
			"Task": [
				{
					"fieldname": "posting_date",
					"fieldtype": "Date",
					"label": "Assigned Date",
					"insert_after": "column_break0",
					"fetch_from": "schedule_cabinet.date",
				},
				{
					"fieldname": "team",
					"fieldtype": "Link",
					"options": "Team",
					"label": "Team",
					"insert_after": "project",
					"fetch_from": "schedule_cabinet.team",
					"fetch_if_empty": 1,
					"read_only_depends_on": "eval: !doc.supervisor;"
				},
				{
					"fieldname": "supervisor",
					"fieldtype": "Data",
					"label": "Assigned Supervisor",
					"insert_after": "team",
					"read_only": 1,
				},
				{
					"fieldname": "cabinet_section",
					"fieldtype": "Section Break",
					"label": "Asset Details",
					"insert_after": "completed_on",
				},
				{
					"fieldname": "schedule_cabinet",
					"fieldtype": "Link",
					"options": "Schedule Cabinet",
					"label": "Schedule Asset Unit",
					"insert_after": "cabinet_section",
					"read_only": 1,
				},
				{
					"fieldname": "asset_unit",
					"fieldtype": "Link",
					"options": "Asset Unit",
					"label": "Asset Unit",
					"insert_after": "schedule_cabinet",
					"read_only": 1,
				},
				{
					"fieldname": "asset_name",
					"fieldtype": "Data",
					"fetch_from": "asset_unit.asset_name",
					"label": "Asset Name",
					"insert_after": "asset_unit",
					"read_only": 1,
				},
				{
					"fieldname": "junction_no",
					"fieldtype": "Data",
					"fetch_from": "asset_unit.junction_no",
					"label": "Junction No",
					"insert_after": "asset_name",
					"read_only": 1,
				},
				{
					"fieldname": "column_break_cabinet",
					"fieldtype": "Column Break",
					"insert_after": "junction_no",
				},
				{
					"fieldname": "latitude",
					"fieldtype": "Data",
					"fetch_from": "asset_unit.latitude",
					"label": "Latitude",
					"insert_after": "column_break_cabinet",
					"read_only": 1,
				},
				{
					"fieldname": "longitude",
					"fieldtype": "Data",
					"fetch_from": "asset_unit.longitude",
					"label": "Longitude",
					"insert_after": "latitude",
					"read_only": 1,
				},
				{
					"fieldname": "rectification_required",
					"fieldtype": "Button",
					"label": "Rectification?",
					"insert_after": "longitude",
					"display_depends_on": "eval: !doc.__islocal && !doc.parent_task"
				},
				{
					"fieldname": "section_break_location",
					"label": "Asset Location",
					"fieldtype": "Section Break",
					"insert_after": "rectification_required",
				},
				{
					"fieldname": "cabinet_location",
					"label": "",
					"fieldtype": "HTML",
					"insert_after": "section_break_location",
				},
				{
					"fieldname": "section_break_tmlg",
					"label": "Time Log",
					"fieldtype": "Section Break",
					"insert_after": "cabinet_location",
					"collapsible": 1,
				},
				{
					"fieldname": "time_log",
					"fieldtype": "Table",
					"label": "",
					"options": "Task Time Log",
					"insert_after": "section_break_tmlg",
					"read_only": 1,
					"cannot_edit_rows": 1,
				},
				{
					"fieldname": "total_time_taken",
					"fieldtype": "Float",
					"label": "Total Time TIme",
					"insert_after": "time_log",
					"read_only": 1
				},
				{
					"fieldname": "section_break_reason",
					"label": "",
					"fieldtype": "Section Break",
					"insert_after": "description",
				},
				{
					"fieldname": "pause_resume_reason",
					"fieldtype": "Small Text",
					"label": "Pause Resume Reason",
					"insert_after": "section_break_reason",
					"read_only": 1
				},
	  		],
			"ToDo": [
				{
					"fieldname": "task_details",
					"fieldtype": "Section Break",
					"label": "Task Details",
					"insert_after": "assignment_rule",
					"collapsible": 1,
				},
				{
					"fieldname": "posting_date",
					"fieldtype": "Date",
					"default": "Today",
					"label": "Date",
					"insert_after": "task_details",
					"read_only": 1,
				},
				{
					"fieldname": "team",
					"fieldtype": "Link",
					"options": "Team",
					"label": "Team",
					"insert_after": "posting_date",
					"read_only": 1,
				},
				{
					"fieldname": "supervisor",
					"fieldtype": "Data",
					"label": "Assigned Supervisor",
					"insert_after": "team",
					"read_only": 1,
				},
				{
					"fieldname": "schedule_asset",
					"fieldtype": "Data",
					"label": "Schedule Cabinet",
					"insert_after": "supervisor",
					"read_only": 1,
				},
				{
					"fieldname": "asset_unit",
					"fieldtype": "Link",
					"options": "Asset Unit",
					"label": "Asset Unit",
					"insert_after": "schedule_asset",
					"read_only": 1,
				},
				{
					"fieldname": "asset_name",
					"fieldtype": "Data",
					"fetch_from": "asset_unit.asset_name",
					"label": "Asset Name",
					"insert_after": "asset_unit",
					"read_only": 1,
				},
				{
					"fieldname": "junction_no",
					"fieldtype": "Data",
					"fetch_from": "asset_unit.junction_no",
					"label": "Junction No",
					"insert_after": "asset_name",
					"read_only": 1,
				},
				{
					"fieldname": "project",
					"fieldtype": "Data",
					"fetch_from": "asset_unit.project",
					"label": "Project",
					"insert_after": "junction_no",
					"read_only": 1,
				},
				{
					"fieldname": "column_break_",
					"fieldtype": "Column Break",
					"insert_after": "project",
				},
				{
					"fieldname": "latitude",
					"fieldtype": "Data",
					"fetch_from": "asset_unit.latitude",
					"label": "Latitude",
					"insert_after": "column_break_",
					"read_only": 1,
				},
				{
					"fieldname": "longitude",
					"fieldtype": "Data",
					"fetch_from": "asset_unit.longitude",
					"label": "Longitude",
					"insert_after": "latitude",
					"read_only": 1,
				},
				{
					"fieldname": "employee_name",
					"fieldtype": "Data",
					"label": "Employee Name",
					"insert_after": "longitude",
					"read_only": 1,
				},
				{
					"fieldname": "phone_number",
					"fieldtype": "Data",
					"label": "Phone Number",
					"insert_after": "employee_name",
					"read_only": 1,
				},
				{
					"fieldname": "crew",
					"fieldtype": "Data",
					"label": "Crew",
					"insert_after": "phone_number",
					"read_only": 1,
				},
				{
					"fieldname": "task_url",
					"fieldtype": "Attach",
					"label": "Task URL",
					"insert_after": "company",
					"read_only": 1,
				},
	  		],
		}
  	)
